meta_product_name: "Osusowake"
meta_title: "Osusowake"
meta_description: "Creating a sense of community through home-cooked meals."
meta_image: "bread.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
